[package]
name = "saturn-v-frontend"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
lsp-types = "0.94"
salsa.workspace = true
smallvec.workspace = true
url.workspace = true
